#include <UI_Object_Stub.h>

using namespace LGui;


BUILDER_STUB_DEFAULT_CONSTRUCTION_FUNC(UI_Object_Stub)

BUILDER_STUB_INITIALIZATION_FUNC(UI_Object_Stub)
{
    BUILDER_STUB_PARENT_INITIALIZATION;
}
